# Generated by Django 4.0.3 on 2022-03-05 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_audio_file', models.FileField(help_text='테스트 음성파일', upload_to='test_audio_file/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(help_text='정답', max_length=50)),
                ('solved_count', models.IntegerField(default=0, help_text='푼 사람 수')),
                ('wrong_count', models.IntegerField(default=0, help_text='틀린 사람 수')),
                ('wrong_answer_rate', models.FloatField(default=0, help_text='오답률')),
                ('paper', models.ForeignKey(help_text='시험', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_user', models.CharField(help_text='유저가 작성한 정답', max_length=50)),
                ('is_correct', models.BooleanField(help_text='정답 여부')),
                ('question', models.ForeignKey(help_text='시험 문제', on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to='papers.question')),
                ('user', models.ForeignKey(help_text='유저가 푼 시험 문제', on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, help_text='총점')),
                ('paper', models.ForeignKey(help_text='시험', on_delete=django.db.models.deletion.CASCADE, related_name='paper_user', to='papers.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
