# Generated by Django 4.0.3 on 2022-03-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='test_audio_file',
            field=models.FileField(blank=True, help_text='테스트 음성파일', null=True, upload_to='test_audio_file/%Y/%m/%d'),
        ),
    ]
