# Generated by Django 4.0 on 2022-03-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_created_at_paperuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
