# Generated by Django 3.1 on 2022-03-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sound_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paperuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
